spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:/Users/tom/IdeaProjects/todos-spring/todo-db'
#    url: 'jdbc:h2:file:J:/Desktop/todos-spring/todo-db'
  jpa:
    hibernate:
      ddl-auto: validate
#      validacja miedzy sql flyway a hibernate co do wersji
management:
  endpoints:
    web:
      exposure:
        include: '*'

keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'TodoApp'
  resource: 'todo-spring-client'
  public-client: true